name: dart_hackathon_1
description: A Dart project for hackathon
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'  # Adjust this line based on your Dart SDK version

dependencies:
  # Your dependencies go here

dev_dependencies:
  test: ^1.20.0 